package generator

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	_ "github.com/go-sql-driver/mysql" // MySQL 驱动
	"vigo/framework/idl"
)

// GenerateAPI 从 IDL 生成 API 代码
func GenerateAPI(input, output, style string) error {
	// 解析 IDL 文件
	apiDef, err := idl.Parse(input)
	if err != nil {
		return fmt.Errorf("解析 IDL 文件失败：%w", err)
	}

	// 创建输出目录
	if err := os.MkdirAll(output, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败：%w", err)
	}

	// 根据风格生成不同的代码
	switch style {
	case "mvc":
		return generateMVC(apiDef, output)
	case "rpc":
		return generateRPC(apiDef, output)
	default:
		return fmt.Errorf("不支持的代码风格：%s", style)
	}
}

// GenerateModel 从数据库表生成模型
func GenerateModel(table, output, dsn string) error {
	if err := os.MkdirAll(output, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败：%w", err)
	}

	// 连接数据库获取表结构
	schema, err := GetTableSchema(table, dsn)
	if err != nil {
		// 如果无法连接数据库，生成示例代码
		fmt.Printf("⚠️ 无法连接数据库，生成示例模型：%v\n", err)
		return generateExampleModel(table, output)
	}

	// 根据实际表结构生成模型
	return generateModelFromSchema(schema, output)
}

// GetTableSchema 连接数据库获取表结构信息
func GetTableSchema(tableName, dsn string) (*TableSchema, error) {
	// 连接数据库
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return nil, fmt.Errorf("数据库连接失败：%w", err)
	}
	defer db.Close()

	// 设置连接参数
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(5)
	db.SetConnMaxLifetime(time.Hour)

	// 查询表结构信息
	query := `
		SELECT 
			COLUMN_NAME,
			COLUMN_TYPE,
			IS_NULLABLE,
			COLUMN_KEY,
			COLUMN_DEFAULT,
			EXTRA,
			COLUMN_COMMENT
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_SCHEMA = DATABASE()
		AND TABLE_NAME = ?
		ORDER BY ORDINAL_POSITION
	`
	
	rows, err := db.Query(query, tableName)
	if err != nil {
		return nil, fmt.Errorf("查询表结构失败：%w", err)
	}
	defer rows.Close()

	// 解析字段信息
	var columns []ColumnSchema
	for rows.Next() {
		var column ColumnSchema
		var columnType, isNullable, columnKey, extra, columnComment *string
		var columnDefault *interface{}

		if err := rows.Scan(
			&column.Name,
			&columnType,
			&isNullable,
			&columnKey,
			&columnDefault,
			&extra,
			&columnComment,
		); err != nil {
			return nil, fmt.Errorf("解析列信息失败：%w", err)
		}

		// 设置字段信息
		if columnType != nil {
			column.Type = *columnType
		}
		if isNullable != nil {
			column.Nullable = *isNullable == "YES"
		}
		if columnKey != nil {
			column.IsPrimary = *columnKey == "PRI"
			column.IsUnique = *columnKey == "UNI"
		}
		if extra != nil {
			column.AutoIncrement = strings.Contains(*extra, "auto_increment")
		}
		if columnComment != nil {
			column.Comment = *columnComment
		}

		columns = append(columns, column)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("遍历结果集失败：%w", err)
	}

	if len(columns) == 0 {
		return nil, fmt.Errorf("表 '%s' 不存在或没有字段", tableName)
	}

	return &TableSchema{
		Name:    tableName,
		Columns: columns,
	}, nil
}

// TableSchema 表结构定义
type TableSchema struct {
	Name    string
	Columns []ColumnSchema
}

// ColumnSchema 列结构定义
type ColumnSchema struct {
	Name          string
	Type          string
	Nullable      bool
	IsPrimary     bool
	IsUnique      bool
	AutoIncrement bool
	Comment       string
}

// generateExampleModel 生成示例模型（当无法连接数据库时）
func generateExampleModel(table, output string) error {
	modelFile := filepath.Join(output, fmt.Sprintf("%s.go", toSnakeCase(table)))
	modelTmpl := `// Code generated by vigoctl. DO NOT EDIT.
// This file was generated at {{.Timestamp}}

package model

import (
	"time"
)

// {{.ModelName}} {{.ModelDesc}}
type {{.ModelName}} struct {
	Id        int64     ` + "`json:\"id\" db:\"id\"`" + `
	// TODO: 添加其他字段
	CreatedAt time.Time ` + "`json:\"created_at\" db:\"created_at\"`" + `
	UpdatedAt time.Time ` + "`json:\"updated_at\" db:\"updated_at\"`" + `
}

// TableName 表名
func (m *{{.ModelName}}) TableName() string {
	return "{{.TableName}}"
}
`

	tmpl, err := template.New("model").Parse(modelTmpl)
	if err != nil {
		return fmt.Errorf("解析模板失败：%w", err)
	}

	data := map[string]interface{}{
		"ModelName": toPascalCase(table),
		"ModelDesc": table + "模型",
		"TableName": table,
		"Timestamp": time.Now().Format("2006-01-02 15:04:05"),
	}

	file, err := os.Create(modelFile)
	if err != nil {
		return fmt.Errorf("创建文件失败：%w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("生成文件失败：%w", err)
	}

	fmt.Printf("✓ 示例模型生成成功：%s\n", modelFile)
	return nil
}

// generateModelFromSchema 根据实际表结构生成模型
func generateModelFromSchema(schema *TableSchema, output string) error {
	modelFile := filepath.Join(output, fmt.Sprintf("%s.go", toSnakeCase(schema.Name)))
	
	// 构建字段定义
	fieldDefinitions := make([]string, 0, len(schema.Columns))
	for _, column := range schema.Columns {
		fieldDef := buildFieldDefinition(column)
		fieldDefinitions = append(fieldDefinitions, fieldDef)
	}

	modelTmpl := `// Code generated by vigoctl. DO NOT EDIT.
// This file was generated at {{.Timestamp}}
// Table: {{.TableName}}

package model

import (
	"time"
)

// {{.ModelName}} {{.ModelDesc}}
type {{.ModelName}} struct {
{{.Fields}}
}

// TableName 表名
func (m *{{.ModelName}}) TableName() string {
	return "{{.TableName}}"
}
`

	tmpl, err := template.New("model").Parse(modelTmpl)
	if err != nil {
		return fmt.Errorf("解析模板失败：%w", err)
	}

	data := map[string]interface{}{
		"ModelName": toPascalCase(schema.Name),
		"ModelDesc": schema.Name + "模型",
		"TableName": schema.Name,
		"Timestamp": time.Now().Format("2006-01-02 15:04:05"),
		"Fields":    strings.Join(fieldDefinitions, "\n"),
	}

	file, err := os.Create(modelFile)
	if err != nil {
		return fmt.Errorf("创建文件失败：%w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("生成文件失败：%w", err)
	}

	fmt.Printf("✓ 模型生成成功 (基于实际表结构)：%s\n", modelFile)
	fmt.Printf("  包含 %d 个字段\n", len(schema.Columns))
	return nil
}

// buildFieldDefinition 构建字段定义
func buildFieldDefinition(column ColumnSchema) string {
	// Go 类型映射
	goType := mapSQLTypeToGo(column.Type)
	
	// JSON 标签
	jsonTag := fmt.Sprintf(`json:"%s"`, column.Name)
	
	// DB 标签
	dbTag := fmt.Sprintf(`db:"%s"`, column.Name)
	
	// 额外属性
	extraTags := ""
	if column.IsPrimary {
		extraTags += " pk"
	}
	if column.AutoIncrement {
		extraTags += " auto_increment"
	}
	
	// 注释
	comment := ""
	if column.Comment != "" {
		comment = " // " + column.Comment
	}
	
	return fmt.Sprintf("\t%s %s `%s %s%s`%s",
		toPascalCase(column.Name),
		goType,
		jsonTag,
		dbTag,
		extraTags,
		comment)
}

// mapSQLTypeToGo 将 SQL 类型映射到 Go 类型
func mapSQLTypeToGo(sqlType string) string {
	sqlType = strings.ToLower(sqlType)
	
	switch {
	case strings.Contains(sqlType, "int"):
		return "int64"
	case strings.Contains(sqlType, "decimal") || strings.Contains(sqlType, "numeric"):
		return "decimal.Decimal"
	case strings.Contains(sqlType, "float") || strings.Contains(sqlType, "double"):
		return "float64"
	case strings.Contains(sqlType, "bool"):
		return "bool"
	case strings.Contains(sqlType, "date") || strings.Contains(sqlType, "time"):
		if strings.Contains(sqlType, "time") {
			return "time.Time"
		}
		return "string"
	case strings.Contains(sqlType, "char") || strings.Contains(sqlType, "text"):
		return "string"
	case strings.Contains(sqlType, "json"):
		return "json.RawMessage"
	case strings.Contains(sqlType, "blob"):
		return "[]byte"
	default:
		return "string"
	}
}

// GenerateService 生成微服务模板
func GenerateService(name, output, serviceType string) error {
	// 创建服务目录结构
	dirs := []string{
		filepath.Join(output, name, "cmd"),
		filepath.Join(output, name, "internal", "handler"),
		filepath.Join(output, name, "internal", "service"),
		filepath.Join(output, name, "internal", "repository"),
		filepath.Join(output, name, "internal", "model"),
		filepath.Join(output, name, "config"),
		filepath.Join(output, name, "deploy"),
	}

	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("创建目录失败：%w", err)
		}
	}

	// 生成 main.go
	mainFile := filepath.Join(output, name, "cmd", "main.go")
	mainTmpl := `package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"
	
	"{{.ImportPath}}/{{.ServiceName}}/internal/handler"
	"{{.ImportPath}}/{{.ServiceName}}/internal/service"
	"github.com/yourorg/vigo/framework/app"
	"github.com/yourorg/vigo/framework/mvc"
	"github.com/yourorg/vigo/framework/middleware"
)

func main() {
	// 初始化应用
	app.Init()

	// 创建服务
	userService := service.NewUserService()
	
	// 创建处理器
	userHandler := handler.NewUserHandler(userService)

	// 注册路由
	router := mvc.NewRouter()
	router.GET("/health", func(ctx *mvc.Context) error {
		return ctx.JSON(map[string]string{"status": "ok"})
	})
	
	// 注册业务路由
	userHandler.RegisterRoutes(router)

	// 使用中间件
	router.Use(middleware.Logger())
	router.Use(middleware.Recovery())

	// 启动应用
	app.Run()
	
	// 优雅停机
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	
	log.Println("服务已停止")
}
`

	if err := writeFile(mainFile, mainTmpl, map[string]interface{}{
		"ServiceName": name,
		"ImportPath":  "github.com/yourorg/vigo",
	}); err != nil {
		return err
	}

	// 生成 config.yaml
	configFile := filepath.Join(output, name, "config", "config.yaml")
	configContent := `# 服务配置
server:
  port: 8080
  mode: release

# 日志配置
log:
  level: info
  path: logs/

# 数据库配置
database:
  driver: mysql
  dsn: "root:password@tcp(localhost:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"

# 服务发现配置
discovery:
  enabled: true
  nacos_addr: http://localhost:8848
  namespace: public
  group: DEFAULT_GROUP

# 链路追踪配置
trace:
  enabled: true
  service_name: {{.ServiceName}}
  jaeger_endpoint: http://localhost:14268/api/traces
  sample_rate: 0.1

# 指标监控配置
metrics:
  enabled: true
  port: 9090
`

	if err := writeFile(configFile, configContent, map[string]interface{}{
		"ServiceName": name,
	}); err != nil {
		return err
	}

	// 生成 Dockerfile
	dockerFile := filepath.Join(output, name, "deploy", "Dockerfile")
	dockerContent := `# 构建阶段
FROM golang:1.21-alpine AS builder

WORKDIR /build

# 安装依赖
RUN apk add --no-cache git

# 复制 go.mod 和 go.sum
COPY go.mod go.sum ./
RUN go mod download

# 复制源代码
COPY . .

# 编译
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/main.go

# 运行阶段
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /app

# 从构建阶段复制二进制文件
COPY --from=builder /build/main .
COPY --from=builder /build/config/ ./config/

EXPOSE 8080

CMD ["./main"]
`

	if err := writeFile(dockerFile, dockerContent, nil); err != nil {
		return err
	}

	fmt.Printf("✓ 微服务模板生成成功：%s\n", filepath.Join(output, name))
	fmt.Printf("  目录结构:\n")
	for _, dir := range dirs {
		fmt.Printf("    - %s\n", dir)
	}

	return nil
}

// GenerateMiddleware 生成中间件模板
func GenerateMiddleware(name, output string) error {
	if err := os.MkdirAll(output, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败：%w", err)
	}

	middlewareFile := filepath.Join(output, fmt.Sprintf("%s.go", toSnakeCase(name)))
	middlewareTmpl := `package middleware

import (
	"time"
	"github.com/yourorg/vigo/framework/mvc"
)

// {{.MiddlewareName}} {{.MiddlewareDesc}}
// 用法：router.Use({{.MiddlewareName}}())
func {{.MiddlewareName}}() mvc.HandlerFunc {
	return func(ctx *mvc.Context) error {
		// TODO: 实现中间件逻辑
		
		// 记录请求开始时间
		start := time.Now()
		
		// 调用下一个处理器
		err := ctx.Next()
		
		// 记录请求耗时
		duration := time.Since(start)
		
		// TODO: 添加自定义逻辑
		// 例如：日志记录、权限验证、限流等
		
		return err
	}
}
`

	if err := writeFile(middlewareFile, middlewareTmpl, map[string]interface{}{
		"MiddlewareName": toPascalCase(name),
		"MiddlewareDesc": name + "中间件",
	}); err != nil {
		return err
	}

	fmt.Printf("✓ 中间件模板生成成功：%s\n", middlewareFile)
	return nil
}

// Upgrade 升级框架版本
func Upgrade() error {
	fmt.Println("检查框架更新...")

	// TODO: 实现版本检查和升级逻辑

	fmt.Println("✓ 框架已是最新版本")
	return nil
}

// 辅助函数

func generateMVC(apiDef *idl.APIDefinition, output string) error {
	// 生成 MVC 风格的代码
	handlerDir := filepath.Join(output, "handler")
	if err := os.MkdirAll(handlerDir, 0755); err != nil {
		return err
	}

	// 生成示例 handler
	handlerFile := filepath.Join(handlerDir, "user_handler.go")
	handlerContent := `package handler

import (
	"github.com/yourorg/vigo/framework/mvc"
	"your-project/internal/service"
)

// UserHandler 用户处理器
type UserHandler struct {
	userService *service.UserService
}

// NewUserHandler 创建用户处理器
func NewUserHandler(svc *service.UserService) *UserHandler {
	return &UserHandler{
		userService: svc,
	}
}

// RegisterRoutes 注册路由
func (h *UserHandler) RegisterRoutes(router *mvc.Router) {
	userGroup := router.Group("/api/v1/users")
	
	userGroup.GET("", h.ListUsers)
	userGroup.GET("/:id", h.GetUser)
	userGroup.POST("", h.CreateUser)
	userGroup.PUT("/:id", h.UpdateUser)
	userGroup.DELETE("/:id", h.DeleteUser)
}

// ListUsers 获取用户列表
func (h *UserHandler) ListUsers(ctx *mvc.Context) error {
	// TODO: 实现业务逻辑
	return ctx.JSON(map[string]string{"message": "list users"})
}

// GetUser 获取用户详情
func (h *UserHandler) GetUser(ctx *mvc.Context) error {
	// TODO: 实现业务逻辑
	return ctx.JSON(map[string]string{"message": "get user"})
}

// CreateUser 创建用户
func (h *UserHandler) CreateUser(ctx *mvc.Context) error {
	// TODO: 实现业务逻辑
	return ctx.JSON(map[string]string{"message": "create user"})
}

// UpdateUser 更新用户
func (h *UserHandler) UpdateUser(ctx *mvc.Context) error {
	// TODO: 实现业务逻辑
	return ctx.JSON(map[string]string{"message": "update user"})
}

// DeleteUser 删除用户
func (h *UserHandler) DeleteUser(ctx *mvc.Context) error {
	// TODO: 实现业务逻辑
	return ctx.JSON(map[string]string{"message": "delete user"})
}
`

	if err := writeFile(handlerFile, handlerContent, nil); err != nil {
		return err
	}

	fmt.Printf("✓ API 代码生成成功 (MVC 风格): %s\n", output)
	return nil
}

func generateRPC(apiDef *idl.APIDefinition, output string) error {
	// 生成 RPC 风格的代码
	return fmt.Errorf("RPC 风格代码生成尚未实现")
}

func writeFile(path, content string, data map[string]interface{}) error {
	// 如果有数据，处理模板
	if data != nil {
		tmpl, err := template.New("file").Parse(content)
		if err != nil {
			return fmt.Errorf("解析模板失败：%w", err)
		}

		var buf strings.Builder
		if err := tmpl.Execute(&buf, data); err != nil {
			return fmt.Errorf("执行模板失败：%w", err)
		}
		content = buf.String()
	}

	return os.WriteFile(path, []byte(content), 0644)
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func toSnakeCase(s string) string {
	return strings.ToLower(s)
}
